spring.application.name=AIBE5_Project2_Team7

spring.config.import=optional:classpath:application-db.properties,optional:file:.env[.properties]

# Hibernate DDL auto (create, create-drop, update, validate, none)
# For development use 'update' to create/update tables automatically. In production prefer 'validate' or manage schema migrations.
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
