export const SIDEBAR_MENUS = [
    { key: 'dashboard', label: '대시보드', icon: 'dashboard' },
    { key: 'work', label: '근무 관리', icon: 'work_history' },
    { key: 'resume', label: '이력서 관리', icon: 'article' },
    { key: 'review', label: '리뷰 관리', icon: 'rate_review' },
    { key: 'scrap', label: '스크랩 공고', icon: 'bookmark' },
    { key: 'info', label: '정보 수정', icon: 'manage_accounts' },
];

export const BUSINESS_TYPE_OPTIONS = [
    { label: '외식(음식점)', value: 'FOOD_RESTAURANT' },
    { label: '카페', value: 'CAFE' },
    { label: '매장관리·판매', value: 'RETAIL_STORE' },
    { label: '서비스', value: 'SERVICE' },
    { label: '운전·배달', value: 'DELIVERY_DRIVER' },
    { label: '현장단순노무', value: 'MANUAL_LABOR' },
];

export const BRAND_OPTIONS = [
    { id: 1, name: '쿠팡', businessType: 'MANUAL_LABOR' },
    { id: 2, name: 'CJ대한통운', businessType: 'MANUAL_LABOR' },
    { id: 3, name: '한진택배', businessType: 'MANUAL_LABOR' },
    { id: 4, name: '롯데택배', businessType: 'MANUAL_LABOR' },
    { id: 5, name: '로젠택배', businessType: 'MANUAL_LABOR' },

    { id: 6, name: 'CU', businessType: 'RETAIL_STORE' },
    { id: 7, name: 'GS25', businessType: 'RETAIL_STORE' },
    { id: 8, name: '세븐일레븐', businessType: 'RETAIL_STORE' },
    { id: 9, name: '이마트24', businessType: 'RETAIL_STORE' },

    { id: 10, name: '스타벅스', businessType: 'CAFE' },
    { id: 11, name: '메가커피', businessType: 'CAFE' },
    { id: 12, name: '투썸플레이스', businessType: 'CAFE' },
    { id: 13, name: '공차', businessType: 'CAFE' },
    { id: 14, name: '매머드커피', businessType: 'CAFE' },
    { id: 15, name: '빽다방', businessType: 'CAFE' },
    { id: 16, name: '컴포즈커피', businessType: 'CAFE' },
    { id: 17, name: '이디야', businessType: 'CAFE' },
    { id: 18, name: '커피빈', businessType: 'CAFE' },

    { id: 19, name: '롯데리아', businessType: 'FOOD_RESTAURANT' },
    { id: 20, name: '맥도날드', businessType: 'FOOD_RESTAURANT' },
    { id: 21, name: '맘스터치', businessType: 'FOOD_RESTAURANT' },
    { id: 22, name: '버거킹', businessType: 'FOOD_RESTAURANT' },
    { id: 23, name: '써브웨이', businessType: 'FOOD_RESTAURANT' },
    { id: 24, name: 'KFC', businessType: 'FOOD_RESTAURANT' },
    { id: 25, name: '도미노피자', businessType: 'FOOD_RESTAURANT' },
    { id: 26, name: '피자헛', businessType: 'FOOD_RESTAURANT' },
    { id: 27, name: '교촌치킨', businessType: 'FOOD_RESTAURANT' },
    { id: 28, name: 'BBQ', businessType: 'FOOD_RESTAURANT' },
    { id: 29, name: 'BHC', businessType: 'FOOD_RESTAURANT' },
    { id: 30, name: '배스킨라빈스', businessType: 'FOOD_RESTAURANT' },
    { id: 31, name: '역전할머니맥주', businessType: 'FOOD_RESTAURANT' },
    { id: 32, name: '한신포차', businessType: 'FOOD_RESTAURANT' },
    { id: 33, name: '투다리', businessType: 'FOOD_RESTAURANT' },
    { id: 34, name: '던킨', businessType: 'FOOD_RESTAURANT' },
    { id: 35, name: '뚜레쥬르', businessType: 'FOOD_RESTAURANT' },
    { id: 36, name: '파리바게뜨', businessType: 'FOOD_RESTAURANT' },

    { id: 37, name: '3POP PC방', businessType: 'RETAIL_STORE' },
    { id: 38, name: '아이센스리그 PC방', businessType: 'RETAIL_STORE' },
    { id: 39, name: '레드포스 PC방', businessType: 'RETAIL_STORE' },

    { id: 40, name: '배달의민족', businessType: 'DELIVERY_DRIVER' },
    { id: 41, name: '쿠팡이츠', businessType: 'DELIVERY_DRIVER' },
    { id: 42, name: '요기요', businessType: 'DELIVERY_DRIVER' },
    { id: 43, name: '땡겨요', businessType: 'DELIVERY_DRIVER' },
];

export const SCRAP_JOBS = [
    {
        id: 1,
        company: '강남역 카페 테라스',
        title: '주말 바리스타 단기 알바 모집',
        tags: ['바리스타', '주말', '단기'],
        pay: '시급 12,000원',
        location: '서울 강남구',
        deadline: '2026-04-25',
        logo: null,
    },
    {
        id: 2,
        company: '역삼동 피트니스 센터',
        title: '오전 헬스 트레이너 파트타임',
        tags: ['트레이너', '오전', '파트타임'],
        pay: '시급 15,000원',
        location: '서울 강남구',
        deadline: '2026-04-30',
        logo: null,
    },
    {
        id: 3,
        company: '성수동 팝업스토어',
        title: '팝업 행사 스태프 모집 (5일)',
        tags: ['행사스태프', '단기', '5일'],
        pay: '일급 100,000원',
        location: '서울 성동구',
        deadline: '2026-05-03',
        logo: null,
    },
    {
        id: 4,
        company: '홍대 이자카야 다이닝',
        title: '홀 서빙 야간 근무자 구합니다',
        tags: ['홀서빙', '야간', '장기'],
        pay: '시급 13,000원',
        location: '서울 마포구',
        deadline: '2026-05-10',
        logo: null,
    },
];
